# docker-compose supports environment variable substitution with the ${VARIABLE-NAME} syntax.
# Environment variables can be sourced in a variety of ways.  One of those ways is through
# a well known '.env' file located in the same folder as the docker-compose.yml file.  See the Docker
# documentation for details: https://docs.docker.com/compose/environment-variables/#the-env-file
# 
# This feature is being used to parameterize some values within this file.  In this directory is also
# a .env file, which is actually a symbolic link to <examples-root>/utils/config.env.  That file
# contains values which get substituted here when docker-compose parses this file.
#
# If you'd like to view the docker-compose.yml file rendered with its environment variable substituions
# you can execute the `docker-compose config` command.  Take note that some demos provide additional 
# environment variable values by exporting them in a script prior to running `docker-compose up`.
---
version: '3.0'
services:
  microservices:
    image: cnfldemos/kafka-streams-examples:5.5.1-DEVX-1881-PR346
    container_name: microservices
    ports:
      - "18894:18894"
    volumes:
      - $PWD/scripts:/opt/docker/scripts
      - $PWD/logs:/opt/docker/logs
      - $PWD/.env:/opt/docker/config/config.env
      - $PWD/stack-configs:/opt/docker/stack-configs
      - $PWD/delta_configs:/opt/docker/delta_configs
    environment:
      LOG_DIR: /opt/docker/logs
      # With Docker, we don't need to worry about cleaning up the subprocesses of the container
      PIDS_FILE: /dev/null
      CONFLUENT: ${CONFLUENT}
      CONFIG_FILE: "/opt/docker/${CONFIG_FILE}"
    command:
      - bash
      - -c
      - |
        set -a
        source /opt/docker/delta_configs/env.delta
        /opt/docker/scripts/run-services.sh

